name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint code
        run: |
          source venv/bin/activate
          black .  # Format code
          flake8 .  # Lint code

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start MLflow server
        run: |
          source venv/bin/activate
          mlflow server --host 0.0.0.0 --port 5000 &
          echo "MLflow server started on port 5000"

      - name: Wait for MLflow server to start
        run: |
          until curl -s http://localhost:5000/api/2.0/mlflow/health > /dev/null; do
            echo "Waiting for MLflow server to start..."
            sleep 5
          done
          echo "MLflow server is up and running!"

      - name: Start FastAPI server
        run: |
          source venv/bin/activate
          uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 &
          echo "FastAPI server started on port 8000"

      - name: Preprocess data
        run: |
          source venv/bin/activate
          python model_pipeline.py preprocess

      - name: Train model
        run: |
          source venv/bin/activate
          export MLFLOW_TRACKING_URI=http://localhost:5000
          python model_pipeline.py train

  notify:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Send email notification via Mailgun
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
            https://api.mailgun.net/v3/sandboxc2aa251d00304af9aba6da6c6b215948.mailgun.org/messages \
            -F from='Mailgun Sandbox <postmaster@sandboxc2aa251d00304af9aba6da6c6b215948.mailgun.org>' \
            -F to='mohamed amor <mohamed.amor@esprit.tn>' \
            -F subject='Pipeline Execution Completed' \
            -F text='Pipeline execution completed successfully!'